apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ k8s_ns }}
  name: bls-shared-data-{{ k8s_ns }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeMode: Filesystem
