apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ base_name }}-nginx
  namespace: {{ k8s_ns }}
  labels:
    build: {{ build_slug }}
    service: {{ base_name }}
data:
    nginx.conf: |
        server {
            listen 8000;
            server_name nginx;

            location /storage/ {
                add_header 'Access-Control-Allow-Origin' * always;
                add_header 'Access-Control-Allow-Methods' 'POST, GET, OPTIONS, PUT, DELETE' always;
                add_header 'Access-Control-Allow-Headers' * always;
                add_header 'Access-Control-Max-Age' 1728000 always;

                if ($request_method = 'OPTIONS') {
                    add_header 'Content-Type' 'text/plain; charset=utf-8';
                    add_header 'Content-Length' 0;
                    return 204;
                }

                alias /var/storage/;
            }
        }
