PASSPORT_MEMORY_CACHE_TTL = 10
PASSPORT_REDIS_CACHE_TTL = 60 * 20
CACHED_USERS_MAX_COUNT = 20000

TOP_BROADCASTERS_MEMORY_CACHE_TTL = 10
TOP_BROADCASTERS_REDIS_CACHE_TTL = 60 * 60

ONLINE_BROADCASTS_MEMORY_CACHE_TTL = 2
ONLINE_BROADCASTS_REDIS_CACHE_TTL = 5

JABBER_MEMORY_CACHE_TTL = 0
JABBER_REDIS_CACHE_TTL = 60

INTERACTIONS_MEMORY_CACHE_TTL = 10
INTERACTIONS_REDIS_CACHE_TTL = 60 * 20

HOTLIST_MEMORY_CACHE_TTL = 10
HOTLIST_REDIS_CACHE_TTL = 60 * 20

FOLLOWING_MEMORY_CACHE_TTL = 10
FOLLOWING_REDIS_CACHE_TTL = 60 * 5

ONLINE_MEMORY_CACHE_TTL = 1
ONLINE_REDIS_CACHE_TTL = 3

GIFTS_MEMORY_CACHE_TTL = 10
GIFTS_REDIS_CACHE_TTL = 60 * 20

BLOCKED_COUNTRY_MEMORY_CACHE_TTL = 10
BLOCKED_COUNTRY_REDIS_CACHE_TTL = 60 * 20

BROADCAST_VIEW_PRIZE = 28
FLIRT_PRIZE = 110
PRIVATE_MSG_PRIZE = 0
BUZZ_PRIZE = 33

IMAGE_CELERY_TASK_TIMEOUT = 30
IMAGE_CELERY_TASK_EXPIRES = 10
IMAGE_CELERY_TASK_TIME_LIMIT = 20

JABBER_HOST = 'localhost'
JABBER_PORT = 5222
JABBER_ADMIN = ''
JABBER_ADMIN_PASSWORD = '123456'

LEGACY_API2_BASIC_PATH = 'api2/v1'
